<a href="https://colab.research.google.com/github/bootstrap0/python-foundations/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1)
print(vec2)
print(vec1+vec2)

[20. 30. 40. 50.]
[100. 110. 120.]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [5]:
vec = np.arange(2,5,1)
print(1/vec)
print(vec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]


In [6]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]


/tmp/ipykernel_6359/3306162440.py:3: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)


In [8]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(mat1)
print(np.min(mat1))
print(np.max(mat1))

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
-9
-1


In [9]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [10]:
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [11]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [9]:
import pandas as pd
calorie_data = pd.DataFrame({'day': ['day1','day2','day3','day4','day5']
                           ,'calories': [450, 300, 345, 520, 600]
                           ,'duration_min': [30, 25, 29, 39, 48]
                           })
calorie_data.iloc[[1,2],[1]]

,calories
1,300
2,345


In [10]:
import datetime
date = datetime.date(2022, 1, 29)
print(date)

2022-01-29


In [17]:
import numpy as np
ls = [1,10,21,35,72]
type(ls)
#np.array(ls)

list

In [19]:
list1 = [9, 8, 7, 6, 5, 4, 3, 2, 1]
np.array([list1])

array([[9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [20]:
np.arange(start=1, stop=10, step=1).reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
array_1 = np.linspace(0,20,6)
array_1

array([ 0.,  4.,  8., 12., 16., 20.])

In [24]:
array_2 = np.arange(0,20,6)
array_2

array([ 0,  6, 12, 18])

In [25]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
mat.mean()

np.float64(131.66666666666666)

In [26]:
a = np.arange(0,20)
a[2:7]

array([2, 3, 4, 5, 6])

In [27]:
np.cos([0, 1, 2, 3, 4])


array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [29]:
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
new_list

[1, 2, 3, 4, 5, 6]

In [30]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
new_array

array([5, 7, 9])

In [34]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1]=5
mat

array([[1, 2, 1],
       [5, 5, 5],
       [1, 8, 9]])

In [35]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[0:3]=5
mat

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [36]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[2]=5
mat

array([[1, 2, 1],
       [4, 5, 9],
       [5, 5, 5]])

In [37]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

21


In [39]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [40]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [42]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
n1 @ n2

matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])